### ISSUE TITLE
Networking is Broken (Second player cannot move)

### ISSUE THREAD

**Issue by pnill** [PermaNulled/T4MP#3]
I've disabled the position and view angle updates which allowed the player to move (of course) however, the new position did not appear on the server which leads me to believe it's not receiving the player snapshots or not parsing them correctly..

That or the indexes aren't matching, this is possibly why they couldn't move previous to the xyz pos and view angles being ignored for the local player server snapshot updates.

The host player does update positions when moved near the player walking animations do not stop though meaning walk_forward,walk_backward,walk_left,and walk_right are not being disabled when they should be... so something strange is going on with the packets there.

**Comment by PermaNulled** [comment]
The host player position is updated properly and local player's position and view angles are being overwritten but strangely their health is not updated when the host attacks their 'dummy'

**Comment by PermaNulled** [comment]
The health issue was actually because the code was missing to handle it in the ProcessServerSnap function, so the only real issue is the position and view angle updates coming from the server for the local player.

Going to disable these and only update other players and see how well that goes.
